### ISSUE TITLE
Error when start running : missing file MSSTDFMT.DLL

### ISSUE THREAD

**Issue by RushFTK** [a9977321/tinywars_dmgcalculator_20191121#1] opened 2019-11-21 09:40 UTC
![7R7()` W~D(Z9 G)0DOL0ZS](https://user-images.githubusercontent.com/20500319/69325939-ee837e00-0c85-11ea-8806-d6bf9a66936f.png)

Suppose to happen on machine that not install VB development enviorment.

**Comment by a9977321** [comment] 2019-11-21 10:33
It might have something to do with the fixed path finding in the exe file. 
See also: newly uploaded vbp file where you can find that 2 other documents are required in the c/windows/syswow64

**Comment by a9977321** [comment] 2019-11-22 04:35
It doesn't work. I will try to think of other solutions while trying VB.NET.

**Comment by a9977321** [comment] 2019-12-25 06:26
The problem is fixed in the VB. NET version.

**Closed as completed by a9977321** 2019-12-25 06:26 UTC
